### ISSUE TITLE
one warning

### ISSUE THREAD

**Issue by ViZhe** [AtomLinter/linter-stylint#7]
Linter-stylint running, but shows only one first warning. When correct it, then after saving shows the next.  	
Installed eslint that works properly. Shows a config limit warnings and is updated on change.

____
win 8.1
atom 0.186.0
all packages last version (linter, linter-eslint, linter-stylint)
stylint global

in .stylintrc 
```
{
...
"maxWarnings": 10,
...
}
```

Terminal:
```
stylint var.styl -c ../../../.stylintrc
```
:(24 Warnings

```
stylint var.styl
```
6 Warnings

**Comment by matthojo** [comment]
I can't seem to duplicate this sorry. What are you Atom Linter settings and config file?

**Comment by ViZhe** [comment]
update to 0.6.0 and run strict mode - result is the same

.stylintrc in root project
```
{
    "borderNone": true,
    "brackets": true,
    "colons": true,

    "colors": true,

    "commaSpace": true,
    "commentSpace": true,
    "cssLiteral": true,
    "depthLimit": 5,
    "duplicates": false,
    "efficient": true,
    "emoji": true,
    "enforceBlockStyle": true,
    "enforceVarStyle": true,
    "extendPref": "@extends",
    "globalDupe": false,

    "indentSpaces": 4,

    "leadingZero": true,
    "maxWarnings": 100,
    "maxWarningsKill": false,
    "mixed": false,
    "namingConvention": false,
    "namingConventionStrict": false,
    "parenSpace": false,
    "placeholders": true,
    "quotePref": "single",
    "semicolons": true,
    "sortOrder": "grouped",
    "stackedProperties": true,
    "universal": false,
    "valid": false,
    "whitespace": true,
    "zeroUnits": true,
    "zIndexDuplicates": false,
    "zIndexNormalize": false
}
```

part of config atom's
```
  linter:
    statusBar: "Show all errors"
    showErrorInline: false
  "linter-eslint":
    disableWhenNoEslintrcFileInPath: true
  "linter-stylint":
    stylintExecutablePath: "C:\\Users\\ViZhe\\AppData\\Roaming\\npm\\node_modules\\stylint\\bin"
```

screenshot:
![2015-05-24-13-30-51](https://cloud.githubusercontent.com/assets/8091902/7787512/66f94904-0219-11e5-8669-2a20df485e1c.png)
